---
- name: Install Docker
  hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true

    - name: Ensure repository key is installed
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ensure docker registry is available
      ansible.builtin.apt_repository:
        repo: 'deb https://download.docker.com/linux/ubuntu bionic stable'
        state: present

    - name: Ensure docker and dependencies are installed
      ansible.builtin.apt:
        name: docker-ce
        update_cache: true
        state: present
